// legacy-vue-app/src/views/Jobs.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { useJobsStore } from '../stores/jobs'
import type { Job } from '../stores/jobs'
import { useAuthStore } from '../stores/auth'
import { 
  Briefcase, 
  Search, 
  Sparkles, 
  Bookmark, 
  BookmarkCheck, 
  MapPin, 
  DollarSign, 
  CheckCircle2, 
  ArrowRight,
  Clock,
  Trash2
} from 'lucide-vue-next'

const jobsStore = useJobsStore()
const authStore = useAuthStore()

const searchInput = ref('')
const selectedType = ref<string>('All')
const selectedTab = ref<'all' | 'saved' | 'applied'>('all')

const jobTypes = ['All', 'Internship', 'Full-time', 'Fellowship']

// Filter opportunities
const filteredJobs = computed(() => {
  return jobsStore.jobs.filter(job => {
    // Search query matches
    const matchesSearch = 
      job.title.toLowerCase().includes(searchInput.value.toLowerCase()) || 
      job.companyName.toLowerCase().includes(searchInput.value.toLowerCase()) ||
      job.requirements.some(r => r.toLowerCase().includes(searchInput.value.toLowerCase()))

    // Type matches
    const matchesType = 
      selectedType.value === 'All' || 
      job.opportunityType === selectedType.value

    // Tabs matches
    if (selectedTab.value === 'saved') {
      return matchesSearch && matchesType && job.status === 'Saved'
    } else if (selectedTab.value === 'applied') {
      return matchesSearch && matchesType && job.status !== 'None' && job.status !== 'Saved'
    }
    
    return matchesSearch && matchesType
  })
})

// Calculate simulated match percentage based on matching skills
const getMatchScore = (jobRequirements: string[]) => {
  const userSkills = authStore.profile.skills
  const matches = jobRequirements.filter(skill => userSkills.includes(skill))
  const score = Math.round((matches.length / jobRequirements.length) * 100)
  return isNaN(score) ? 50 : Math.max(30, score) // Ensure a baseline score
}

const getMatchColor = (score: number) => {
  if (score >= 80) return 'text-brand-success bg-emerald-50'
  if (score >= 50) return 'text-brand-warning bg-amber-50'
  return 'text-brand-textSecondary bg-slate-100'
}

const handleBookmarkToggle = (job: Job) => {
  if (job.status === 'Saved') {
    jobsStore.updateStatus(job.id, 'None')
  } else if (job.status === 'None') {
    jobsStore.saveJob(job.id)
  }
}

const handleStatusAdvance = (jobId: string, currentStatus: Job['status']) => {
  let nextStatus: Job['status'] = 'Applied'
  if (currentStatus === 'Applied') nextStatus = 'Interview'
  else if (currentStatus === 'Interview') nextStatus = 'Offer'
  else if (currentStatus === 'Offer') nextStatus = 'None'

  jobsStore.updateStatus(jobId, nextStatus)
}
</script>

<template>
  <div class="space-y-6">
    
    <!-- Page Header Banner -->
    <div class="bg-gradient-to-r from-sky-50 to-slate-50 border border-brand-border rounded-3xl p-6 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 shadow-premium-sm">
      <div class="space-y-1">
        <h2 class="text-xl font-extrabold text-brand-textPrimary flex items-center gap-2">
          <Briefcase class="w-6 h-6 text-brand-accent" /> Opportunities Board
        </h2>
        <p class="text-brand-textSecondary text-xs font-semibold">
          Discover jobs, internships, and research fellowships. Tailor your resume to fit high-probability match recommendations.
        </p>
      </div>

      <div class="flex items-center gap-3 bg-white px-4 py-2 border border-brand-border rounded-xl shadow-premium-sm">
        <CheckCircle2 class="w-5 h-5 text-brand-success" />
        <div class="text-left">
          <span class="text-[9px] font-bold text-brand-textSecondary uppercase block">Applications</span>
          <span class="text-xs font-black text-brand-textPrimary">{{ jobsStore.appliedJobs.length }} Tracked</span>
        </div>
      </div>
    </div>

    <!-- Opportunities Hub Navigation Tabs -->
    <div class="flex border-b border-brand-border">
      <button 
        @click="selectedTab = 'all'"
        class="px-5 py-3 text-xs font-bold border-b-2 transition-all duration-200"
        :class="[
          selectedTab === 'all' 
            ? 'border-brand-accent text-brand-accent' 
            : 'border-transparent text-brand-textSecondary hover:text-brand-textPrimary'
        ]"
      >
        All Opportunities
      </button>
      <button 
        @click="selectedTab = 'saved'"
        class="px-5 py-3 text-xs font-bold border-b-2 transition-all duration-200"
        :class="[
          selectedTab === 'saved' 
            ? 'border-brand-accent text-brand-accent' 
            : 'border-transparent text-brand-textSecondary hover:text-brand-textPrimary'
        ]"
      >
        Bookmarked ({{ jobsStore.savedJobs.length }})
      </button>
      <button 
        @click="selectedTab = 'applied'"
        class="px-5 py-3 text-xs font-bold border-b-2 transition-all duration-200"
        :class="[
          selectedTab === 'applied' 
            ? 'border-brand-accent text-brand-accent' 
            : 'border-transparent text-brand-textSecondary hover:text-brand-textPrimary'
        ]"
      >
        Applied Tracking ({{ jobsStore.appliedJobs.length }})
      </button>
    </div>

    <!-- Search Controls Bar -->
    <div class="flex flex-col md:flex-row md:items-center justify-between gap-4">
      <!-- Search Input -->
      <div class="relative w-full md:w-80">
        <span class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
          <Search class="w-4 h-4 text-brand-textSecondary" />
        </span>
        <input 
          type="text" 
          v-model="searchInput"
          placeholder="Search company, title, keywords..."
          class="w-full pl-9 pr-4 py-2 text-xs border border-brand-border rounded-xl bg-white text-brand-textPrimary placeholder-brand-textSecondary focus:outline-none focus:border-brand-accent shadow-premium-sm"
        />
      </div>

      <!-- Type filter pills -->
      <div class="flex items-center gap-1.5 overflow-x-auto pb-1 max-w-full scrollbar-none">
        <button 
          v-for="t in jobTypes" 
          :key="t"
          @click="selectedType = t"
          class="px-3.5 py-1.5 rounded-full text-xs font-bold transition-all duration-200 border border-brand-border"
          :class="[
            selectedType === t 
              ? 'bg-brand-textPrimary text-white border-brand-textPrimary shadow-premium-sm' 
              : 'bg-white hover:bg-slate-50 text-brand-textSecondary'
          ]"
        >
          {{ t }}
        </button>
      </div>
    </div>

    <!-- Active List -->
    <div class="space-y-4">
      <div 
        v-for="job in filteredJobs" 
        :key="job.id"
        class="bg-brand-cardBg border border-brand-border rounded-2xl p-5 shadow-premium flex flex-col lg:flex-row lg:items-center justify-between gap-6 hover:shadow-premium-hover hover:border-brand-accent transition-all duration-300"
      >
        
        <!-- Job Meta Details -->
        <div class="flex items-start gap-4">
          <div class="w-12 h-12 bg-slate-50 border border-brand-border rounded-xl flex items-center justify-center text-xl flex-shrink-0">
            {{ job.companyLogo }}
          </div>
          
          <div class="space-y-1.5 overflow-hidden">
            <div class="flex items-center gap-2 flex-wrap">
              <h3 class="text-sm font-extrabold text-brand-textPrimary truncate leading-snug">
                {{ job.title }}
              </h3>
              
              <!-- Job type badge -->
              <span class="px-2 py-0.5 rounded text-[8px] font-bold bg-slate-100 text-brand-textSecondary uppercase border">
                {{ job.opportunityType }}
              </span>

              <!-- Matching score indicator -->
              <span 
                class="px-2 py-0.5 rounded text-[8px] font-bold uppercase tracking-wider flex items-center gap-0.5"
                :class="getMatchColor(getMatchScore(job.requirements))"
              >
                <Sparkles class="w-2.5 h-2.5" /> {{ getMatchScore(job.requirements) }}% Match
              </span>
            </div>
            
            <p class="text-xs text-brand-textSecondary font-semibold">
              {{ job.companyName }}
            </p>

            <div class="flex items-center gap-4 text-[10px] text-brand-textSecondary font-medium flex-wrap pt-0.5">
              <span class="flex items-center gap-1">
                <MapPin class="w-3.5 h-3.5" /> {{ job.location }} {{ job.remote ? '(Remote)' : '' }}
              </span>
              <span class="flex items-center gap-1">
                <DollarSign class="w-3.5 h-3.5" /> {{ job.salaryRange }}
              </span>
              <span v-if="job.appliedAt" class="flex items-center gap-1">
                <Clock class="w-3.5 h-3.5" /> Applied on: {{ job.appliedAt }}
              </span>
            </div>
          </div>
        </div>

        <!-- Requirements Tag list -->
        <div class="hidden xl:flex flex-wrap gap-1 max-w-xs">
          <span 
            v-for="req in job.requirements" 
            :key="req"
            class="px-2 py-0.5 rounded text-[8px] font-bold bg-slate-50 text-brand-textSecondary border"
          >
            {{ req }}
          </span>
        </div>

        <!-- Right Side: Pipeline Stepper OR Application action triggers -->
        <div class="flex items-center justify-between sm:justify-end gap-4 border-t lg:border-t-0 pt-4 lg:pt-0 border-dashed border-brand-border">
          
          <!-- Stepper view if applied -->
          <div 
            v-if="job.status !== 'None' && job.status !== 'Saved'"
            class="flex items-center gap-2"
          >
            <!-- Stepper indicators -->
            <button 
              @click="handleStatusAdvance(job.id, job.status)"
              class="px-3 py-1.5 rounded-xl text-[10px] font-bold border transition-colors flex items-center gap-1"
              :class="[
                job.status === 'Applied' ? 'bg-sky-50 text-brand-accent border-sky-100' :
                job.status === 'Interview' ? 'bg-amber-50 text-brand-warning border-amber-100' :
                job.status === 'Offer' ? 'bg-emerald-50 text-brand-success border-emerald-100' : 
                'bg-red-50 text-brand-danger border-red-100'
              ]"
            >
              Stage: {{ job.status }} <ArrowRight class="w-3 h-3" />
            </button>
          </div>

          <!-- Application control buttons -->
          <div class="flex items-center gap-2">
            <!-- Bookmark -->
            <button 
              v-if="job.status === 'None' || job.status === 'Saved'"
              @click="handleBookmarkToggle(job)"
              class="p-2.5 rounded-xl border border-brand-border hover:border-brand-accent hover:text-brand-accent text-brand-textSecondary transition-colors"
              title="Bookmark Opportunity"
            >
              <BookmarkCheck v-if="job.status === 'Saved'" class="w-4 h-4 text-brand-accent" />
              <Bookmark v-else class="w-4 h-4" />
            </button>

            <!-- Apply -->
            <button 
              v-if="job.status === 'None' || job.status === 'Saved'"
              @click="jobsStore.applyJob(job.id)"
              class="px-4 py-2 bg-brand-accent text-white font-bold text-xs rounded-xl shadow-premium hover:bg-sky-700 transition-colors flex items-center gap-1"
            >
              Apply <ArrowRight class="w-3.5 h-3.5" />
            </button>
            
            <!-- Delete application tracker -->
            <button 
              v-else 
              @click="jobsStore.updateStatus(job.id, 'None')"
              class="p-2 rounded-xl text-brand-textSecondary hover:text-brand-danger hover:bg-red-50 transition-colors"
              title="Withdraw application tracking"
            >
              <Trash2 class="w-4.5 h-4.5" />
            </button>
          </div>

        </div>

      </div>
    </div>

    <!-- Empty search list state -->
    <div 
      v-if="filteredJobs.length === 0" 
      class="text-center py-20 bg-brand-cardBg border border-brand-border border-dashed rounded-3xl"
    >
      <Briefcase class="w-10 h-10 text-brand-textSecondary mx-auto opacity-40" />
      <h3 class="font-bold text-sm text-brand-textPrimary mt-3">No opportunities match</h3>
      <p class="text-xs text-brand-textSecondary mt-1">Try adapting your filters or searching another keyword.</p>
    </div>

  </div>
</template>

// frontend/src/app/(dashboard)/jobs/page.tsx
'use client';

import React, { useState, useEffect } from 'react';
import { api } from '@/lib/api';
import { useAuth } from '@/context/AuthContext';
import {
  Briefcase, MapPin, DollarSign, Sparkles, Search,
  ArrowRight, CheckCircle, TrendingUp, RefreshCw, Filter, Clock,
  Building2, ChevronDown, ChevronUp
} from 'lucide-react';

interface Opportunity {
  id: string;
  title: string;
  companyName: string;
  companyType: 'STARTUP' | 'ENTERPRISE';
  location: string;
  salary?: string;
  remote: boolean;
  type: 'JOB' | 'INTERNSHIP' | 'HACKATHON' | 'SCHOLARSHIP';
  skillsRequired: string[];
  description: string;
  matchScore: number;
  matchExplanation: string;
}

interface Application {
  id: string;
  opportunityId: string;
  status: 'APPLIED' | 'SHORTLISTED' | 'INTERVIEW' | 'OFFER' | 'REJECTED';
  appliedAt: string;
  opportunity: Opportunity;
}

const TYPE_COLORS: Record<string, string> = {
  JOB: 'bg-blue-50 text-blue-700 border-blue-200',
  INTERNSHIP: 'bg-sky-50 text-sky-700 border-sky-200',
  HACKATHON: 'bg-violet-50 text-violet-700 border-violet-200',
  SCHOLARSHIP: 'bg-amber-50 text-amber-700 border-amber-200',
};

const COMPANY_TYPE_COLORS: Record<string, string> = {
  STARTUP: 'bg-purple-50 text-purple-700 border-purple-200',
  ENTERPRISE: 'bg-emerald-50 text-emerald-700 border-emerald-200',
};

const STATUSES = ['APPLIED', 'SHORTLISTED', 'INTERVIEW', 'OFFER', 'REJECTED'];

export default function OpportunitiesHub() {
  const { refreshUser } = useAuth();
  const [ops, setOps] = useState<Opportunity[]>([]);
  const [applications, setApplications] = useState<Application[]>([]);
  const [loading, setLoading] = useState(false);
  const [search, setSearch] = useState('');
  const [typeFilter, setTypeFilter] = useState('');
  const [companyTypeFilter, setCompanyTypeFilter] = useState('');
  const [remoteOnly, setRemoteOnly] = useState(false);
  const [tab, setTab] = useState<'browse' | 'pipeline'>('browse');
  const [applyingId, setApplyingId] = useState<string | null>(null);
  const [expandedReason, setExpandedReason] = useState<Record<string, boolean>>({});

  const fetchOps = async () => {
    setLoading(true);
    try {
      const q = new URLSearchParams();
      if (search) q.set('search', search);
      if (typeFilter) q.set('type', typeFilter);
      if (companyTypeFilter) q.set('companyType', companyTypeFilter);
      if (remoteOnly) q.set('remote', 'true');
      const res = await api.get(`/opportunities?${q}`);
      setOps(res.data);
    } catch (e) { console.error(e); } finally { setLoading(false); }
  };

  const fetchApps = async () => {
    try {
      const res = await api.get('/opportunities/applications');
      setApplications(res.data);
    } catch (e) { console.error(e); }
  };

  useEffect(() => { fetchOps(); fetchApps(); }, [search, typeFilter, companyTypeFilter, remoteOnly]);

  const handleApply = async (opId: string) => {
    setApplyingId(opId);
    try {
      await api.post(`/opportunities/apply/${opId}`);
      fetchOps(); fetchApps();
      await refreshUser();
    } catch (e: any) {
      alert(e.response?.data?.error || 'Could not apply. Please try again.');
    } finally { setApplyingId(null); }
  };

  const advanceStatus = async (appId: string, status: string) => {
    await api.put(`/opportunities/applications/${appId}/status`, { status });
    fetchApps();
  };

  const toggleReason = (id: string) => {
    setExpandedReason(prev => ({ ...prev, [id]: !prev[id] }));
  };

  const isApplied = (id: string) => applications.some(a => a.opportunityId === id);

  const formatBoldText = (text: string) => {
    if (!text) return '';
    return text.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div>
          <h1 className="text-2xl font-black text-slate-900">Opportunities Hub</h1>
          <p className="text-slate-500 text-sm mt-1">Ingesting live job & internship openings from startups and big tech enterprises</p>
        </div>
        <div className="flex bg-slate-100 p-1 rounded-xl shrink-0">
          <button
            onClick={() => setTab('browse')}
            className={`px-4 py-2 rounded-lg text-sm font-semibold transition-all ${tab === 'browse' ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-500 hover:text-slate-800'}`}
          >
            Browse
          </button>
          <button
            onClick={() => setTab('pipeline')}
            className={`px-4 py-2 rounded-lg text-sm font-semibold transition-all ${tab === 'pipeline' ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-500 hover:text-slate-800'}`}
          >
            My Applications {applications.length > 0 && <span className="ml-1.5 text-[11px] font-bold bg-sky-100 text-sky-700 px-1.5 py-0.5 rounded-full">{applications.length}</span>}
          </button>
        </div>
      </div>

      {tab === 'browse' ? (
        <div className="space-y-5">
          {/* Filters */}
          <div className="bg-white border border-slate-200 rounded-2xl p-4 flex flex-col xl:flex-row gap-3 items-center">
            <div className="relative flex-1 w-full">
              <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
              <input
                type="text"
                placeholder="Search by role, company, or required skill..."
                value={search}
                onChange={e => setSearch(e.target.value)}
                className="w-full pl-10 pr-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm text-slate-800 focus:outline-none focus:border-sky-400 focus:bg-white transition-colors placeholder:text-slate-400"
              />
            </div>
            <div className="flex flex-wrap gap-3 items-center w-full xl:w-auto justify-end">
              <select
                value={typeFilter}
                onChange={e => setTypeFilter(e.target.value)}
                className="bg-slate-50 border border-slate-200 text-sm text-slate-700 font-medium rounded-xl px-4 py-2.5 focus:outline-none focus:border-sky-400 transition-colors"
              >
                <option value="">All Formats</option>
                <option value="JOB">Jobs</option>
                <option value="INTERNSHIP">Internships</option>
              </select>

              <select
                value={companyTypeFilter}
                onChange={e => setCompanyTypeFilter(e.target.value)}
                className="bg-slate-50 border border-slate-200 text-sm text-slate-700 font-medium rounded-xl px-4 py-2.5 focus:outline-none focus:border-sky-400 transition-colors"
              >
                <option value="">All Scales</option>
                <option value="STARTUP">Startups</option>
                <option value="ENTERPRISE">Enterprise / Big Tech</option>
              </select>

              <label className="flex items-center gap-2 text-sm font-medium text-slate-600 cursor-pointer select-none">
                <input type="checkbox" checked={remoteOnly} onChange={e => setRemoteOnly(e.target.checked)} className="rounded text-sky-600 focus:ring-sky-400" />
                Remote Only
              </label>
              <button onClick={fetchOps} className="p-2.5 text-slate-400 hover:text-sky-600 hover:bg-sky-50 border border-slate-200 hover:border-sky-200 rounded-xl transition-colors" title="Refresh">
                <RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />
              </button>
            </div>
          </div>

          {/* Cards Grid */}
          {ops.length === 0 ? (
            <div className="bg-white border border-slate-200 rounded-2xl p-16 text-center">
              <Briefcase className="h-10 w-10 text-slate-200 mx-auto mb-3" />
              <p className="text-slate-500 font-semibold">No opportunities matched</p>
              <p className="text-slate-400 text-sm mt-1">Try adjusting your scale, formatting, or keyword searches</p>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
              {ops.map(op => {
                let opSkills: string[] = [];
                try {
                  opSkills = typeof op.skillsRequired === 'string' ? JSON.parse(op.skillsRequired) : op.skillsRequired || [];
                } catch {
                  opSkills = op.skillsRequired || [];
                }
                const applied = isApplied(op.id);
                const applying = applyingId === op.id;
                const isExpanded = !!expandedReason[op.id];
                
                return (
                  <div
                    key={op.id}
                    className="bg-white border border-slate-200 rounded-2xl p-5 flex flex-col justify-between hover:border-slate-300 hover:shadow-md hover:-translate-y-0.5 transition-all duration-200"
                  >
                    <div>
                      {/* Top Badging Row */}
                      <div className="flex items-start justify-between gap-3 mb-3">
                        <div className="flex flex-wrap items-center gap-1.5">
                          <span className={`text-[10px] font-black uppercase px-2.5 py-1 rounded-full border ${TYPE_COLORS[op.type] || 'bg-slate-50 text-slate-600'}`}>
                            {op.type}
                          </span>
                          <span className={`text-[10px] font-black uppercase px-2.5 py-1 rounded-full border ${COMPANY_TYPE_COLORS[op.companyType] || 'bg-slate-50 text-slate-600'}`}>
                            {op.companyType === 'STARTUP' ? 'Startup' : 'Enterprise'}
                          </span>
                        </div>

                        <div className={`flex items-center gap-1 px-2.5 py-1.5 rounded-xl border text-xs font-black shrink-0 ${
                          op.matchScore >= 75 ? 'bg-emerald-50 text-emerald-700 border-emerald-200 shadow-sm shadow-emerald-500/5' : 'bg-amber-50 text-amber-700 border-amber-200'
                        }`}>
                          <Sparkles className="h-3.5 w-3.5 text-indigo-500 animate-pulse" />
                          {op.matchScore}% Match
                        </div>
                      </div>

                      {/* Header details */}
                      <div className="mb-3">
                        <h3 className="font-bold text-slate-900 text-base leading-tight">{op.title}</h3>
                        <p className="text-slate-500 text-sm font-semibold mt-0.5 flex items-center gap-1.5">
                          <Building2 className="h-3.5 w-3.5 text-slate-400" />
                          {op.companyName}
                        </p>
                      </div>

                      {/* Meta location & salary */}
                      <div className="flex flex-wrap gap-3 text-xs text-slate-500 mb-3">
                        <span className="flex items-center gap-1"><MapPin className="h-3.5 w-3.5 text-slate-400" />{op.location}{op.remote ? ' · Remote' : ''}</span>
                        {op.salary && <span className="flex items-center gap-1"><DollarSign className="h-3.5 w-3.5 text-slate-400" />{op.salary}</span>}
                      </div>

                      <p className="text-slate-600 text-sm leading-relaxed mb-3">{op.description}</p>

                      {/* Required skills */}
                      {opSkills.length > 0 && (
                        <div className="flex flex-wrap gap-1.5 mb-4">
                          {opSkills.map(s => (
                            <span key={s} className="text-[11px] font-medium bg-slate-100 text-slate-600 px-2 py-0.5 rounded-md border border-slate-150">{s}</span>
                          ))}
                        </div>
                      )}

                      {/* RAG Reasoning Accordion */}
                      {op.matchExplanation && (
                        <div className="mb-4">
                          <button
                            type="button"
                            onClick={() => toggleReason(op.id)}
                            className="flex items-center gap-1 text-xs font-bold text-indigo-600 hover:text-indigo-700 transition-colors"
                          >
                            <Sparkles className="h-3.5 w-3.5" />
                            <span>{isExpanded ? 'Hide AI Compatibility Match' : 'Reveal AI Compatibility Match'}</span>
                            {isExpanded ? <ChevronUp className="h-3.5 w-3.5" /> : <ChevronDown className="h-3.5 w-3.5" />}
                          </button>
                          
                          {isExpanded && (
                            <div className="mt-2.5 p-4 bg-gradient-to-br from-indigo-50/30 via-sky-50/15 to-transparent border border-indigo-100/50 rounded-xl text-xs text-slate-700 leading-relaxed shadow-inner">
                              <p dangerouslySetInnerHTML={{ __html: formatBoldText(op.matchExplanation) }} />
                            </div>
                          )}
                        </div>
                      )}
                    </div>

                    {/* Apply Trigger */}
                    <button
                      onClick={() => !applied && handleApply(op.id)}
                      disabled={applied || applying}
                      className={`w-full flex items-center justify-center gap-2 py-2.5 rounded-xl text-sm font-semibold transition-all ${
                        applied
                          ? 'bg-emerald-50 border border-emerald-200 text-emerald-700 cursor-default'
                          : 'bg-sky-600 hover:bg-sky-700 text-white shadow-sm'
                      }`}
                    >
                      {applied ? (
                        <><CheckCircle className="h-4 w-4" /> Applied</>
                      ) : applying ? (
                        'Submitting...'
                      ) : (
                        <>Apply Now <ArrowRight className="h-4 w-4" /></>
                      )}
                    </button>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      ) : (
        /* Application tracker pipeline */
        <div className="bg-white border border-slate-200 rounded-2xl p-6 space-y-5 shadow-sm shadow-slate-100/50">
          <div className="flex items-center gap-2 border-b border-slate-100 pb-4">
            <TrendingUp className="h-5 w-5 text-sky-600" />
            <h2 className="font-bold text-slate-900 text-base">Application Tracker</h2>
          </div>

          {applications.length === 0 ? (
            <div className="text-center py-16 border border-dashed border-slate-200 rounded-xl">
              <Briefcase className="h-10 w-10 text-slate-200 mx-auto mb-3" />
              <p className="text-slate-500 font-semibold text-sm">No applications yet</p>
              <p className="text-slate-400 text-xs mt-1">Browse listings and hit Apply to track them here</p>
              <button onClick={() => setTab('browse')} className="mt-4 inline-flex items-center gap-1 text-sky-600 text-sm font-semibold hover:underline">
                Browse opportunities →
              </button>
            </div>
          ) : (
            <div className="space-y-4">
              {applications.map(app => (
                <div key={app.id} className="border border-slate-200 rounded-xl p-5">
                  <div className="flex flex-col lg:flex-row lg:items-center gap-4">
                    <div className="flex-1 min-w-0">
                      <p className="font-bold text-slate-900 text-sm">{app.opportunity.title}</p>
                      <p className="text-slate-500 text-xs mt-0.5">{app.opportunity.companyName} · {app.opportunity.location}</p>
                      <div className="flex items-center gap-1.5 mt-1.5 text-slate-400 text-xs">
                        <Clock className="h-3.5 w-3.5" />
                        Applied {new Date(app.appliedAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
                      </div>
                    </div>

                    {/* Progress tracking steps */}
                    <div className="flex flex-wrap items-center gap-1.5">
                      {STATUSES.map(st => {
                        const idx = STATUSES.indexOf(app.status);
                        const stIdx = STATUSES.indexOf(st);
                        const isActive = app.status === st;
                        const isPast = stIdx <= idx;
                        return (
                          <span
                            key={st}
                            className={`text-[10px] font-bold px-2.5 py-1 rounded-full border transition-colors ${
                              isActive
                                ? st === 'REJECTED' ? 'bg-red-500 border-red-500 text-white' : 'bg-sky-600 border-sky-600 text-white'
                                : isPast && st !== 'REJECTED'
                                ? 'bg-sky-50 border-sky-200 text-sky-600'
                                : 'bg-white border-slate-200 text-slate-300'
                            }`}
                          >
                            {st.charAt(0) + st.slice(1).toLowerCase()}
                          </span>
                        );
                      })}
                    </div>

                    {/* Advance pipeline */}
                    <select
                      value={app.status}
                      onChange={e => advanceStatus(app.id, e.target.value)}
                      className="bg-slate-50 border border-slate-200 text-xs text-slate-700 font-semibold rounded-xl px-3 py-2 focus:outline-none focus:border-sky-400 shrink-0"
                    >
                      {STATUSES.map(s => <option key={s} value={s}>{s.charAt(0) + s.slice(1).toLowerCase()}</option>)}
                    </select>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
